version: '3.8'

services:

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - project2-network

  kafka:
    container_name: kafka
    hostname: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - project2-network

  nifi:
    container_name: nifi
    build: ./nifi/
    ports:
      - "8443:8443"
      - "8082:8082"
    hostname: nifi
    tty: true
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY}
      - NIFI_HOME=/opt/nifi/nifi-current
    networks:
      - project2-network

  flink-jobmanager:
    #image: flink:latest
    build:
      context: ./flink/
      dockerfile: jobmanager.dockerfile
    container_name: flink-jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    command: |
      jobmanager
    volumes:
      - ../Results:/Results
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
    #    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    #        metrics.latency.interval: 1000
    tty: true
    networks:
      - project2-network

  flink-taskmanager:
    build:
      context: ./flink/
      dockerfile: taskmanager.dockerfile
    container_name: flink-taskmanager
    hostname: taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    volumes:
      - ../Results:/Results
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        metrics.reporters: prom
        metrics.latency.interval: 1000
    tty: true
    networks:
      - project2-network

networks:
  project2-network:
    driver: bridge
    name: project2-network
