jobmanager.rpc.address: jobmanager             # Indirizzo del JobManager
jobmanager.rpc.port: 6123
jobmanager.memory.process.size: 1024m          # Memoria totale del processo del JobManager

taskmanager.memory.process.size: 1024m         # Memoria totale del processo di ciascun TaskManager
taskmanager.rpc.port: 6122
taskmanager.numberOfTaskSlots: 2